version: '3'

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    container_name: mzc-django
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./static:/app/static
      - ./media:/app/media
      - ./templates:/app/templates
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=temp_debdb
      - DB_USER=temp_devuser
      - DB_PASS=temp_dev_pw_w^-aeoifh10(29d3oisd12z
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: mzc_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
      - ./templates:/app/templates
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:13
    container_name: mzc_postgres_db
    volumes:
      - mzc_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=temp_debdb
      - POSTGRES_USER=temp_devuser
      - POSTGRES_PASSWORD=temp_dev_pw_w^-aeoifh10(29d3oisd12z

volumes:
  mzc_db_volume: